Basic If-Else Statements:

1. Write a Python program to check if a given number is positive or negative.

In [26]:
#Define a function to check whether a number is positive or negative
def check_num():

    #Input number
    num = int(input("Input any number"))

    #Using if-else conditions to check the number
    if num>0:
        print("It is a positive number")
    elif num<0:
        print("It is a negative number")

check_num()
check_num()
check_num()

    

Input any number 5


It is a positive number


Input any number -5


It is a negative number


Input any number 0


2. Create a program that determines if a person is eligible to vote based on their age.

In [5]:
#Defining a function to check the voting eligibility

def vote_elig(age):
    if age>=18:
        print("Eligible to vote")
    else:
        print("Not eligible to vote")
vote_elig(22)
vote_elig(12)

Eligible to vote
Not eligible to vote


3. Develop a program to find the maximum of two numbers using if-else statements.

In [8]:
#Defining a function that compares two numbers
def compare():
    num1 = int(input("Input the first number"))
    num2 = int(input("Input the second number"))

    if num1>num2:
        print(num1, "is greater than", num2)
    elif num2>num1:
        print(num2, "is greater than", num1)
    else:
        print(num1, "is equal to", num2)
        
compare()
compare()
compare()

Input the first number 55
Input the second number 44


55 is greater than 44


Input the first number 22
Input the second number 25


25 is greater than 22


Input the first number 23
Input the second number 23


23 is equal to 23


4. Write a Python script to classify a given year as a leap year or not.

In [10]:
#Definning a function to checl leap year
def if_leap(year):
    if year%100==0:
        if year%400==0:
            print("Leap Year")
        else:
            print("Not a leap year")
    elif year%4==0:
        print("Leap year")
    else:
        print("Not a leap year")
        
if_leap(2023)
if_leap(2024)
if_leap(2000)
if_leap(2100)

Not a leap year
Leap year
Leap Year
Not a leap year


5. Create a program that checks whether a character is a vowel or a consonant.

In [12]:
def check_vowel_cons(char):
    if char in 'AEIOUaeiou':
        print(char, "is a vowel")
    else:
        print(char, "is a consonant")

check_vowel_cons('N')
check_vowel_cons('U')

N is a consonant
U is a vowel


6. Implement a program to determine whether a given number is even or odd.

In [13]:
def check_odd_even(num):
    if num%2==0:
        print(num, "is even")
    else:
        print(num, "is odd")

check_odd_even(55)
check_odd_even(22)

55 is odd
22 is even


7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.

In [14]:
def abs_value(num):
    if num<0:
        print("Absolute value:", -(num))
    else:
        print("Absolute value:", num)
        
abs_value(-20.5)
abs_value(33.0)

Absolute value: 20.5
Absolute value: 33.0


8. Develop a program that determines the largest of three given numbers using if-else statements.

In [16]:
def largest_num(a,b,c):
    if a>b and a>c:
        print(a, " is the greatest")
    elif b>a and b>c:
        print(b, " is the greatest")
    elif c>a and c>b:
        print(c, " is the greatest")
    
largest_num(2,3,5)
largest_num(9,2,11)

5  is the greatest
11  is the greatest


9. Create a program that checks if a given string is a palindrome.

In [13]:
def check_palindrome():
    string = input("Enter any string: ").lower()
    if string == string[::-1]:
        print("It is a palindrome")
    else:
        print("Not a Palindrome")
              

check_palindrome()
check_palindrome()

Enter any string:  Shalini


Not a Palindrome


Enter any string:  Naman


It is a palindrome


10. Write a Python program to calculate the grade based on a student's score.

In [14]:
def score_to_grade(score):
    if score>=85 and score<=100:
        print("Grade A")
    elif score>=70 and score<=84:
        print("Grade B")
    elif score>=55 and score<=69:
        print("Grade C")
    elif score>=40 and score<=54:
        print("Grade D")
    elif score<=39 and score>=0:
        print("Grade E")
    else:
        print("Invalid Score Entered")
        
score_to_grade(56.4)
score_to_grade(86.3)
score_to_grade(895)

Grade C
Grade A
Invalid Score Entered


Nested If-Else Statements:

11. Write a program to find the largest among three numbers using nested if-else statements

In [16]:
def largest_num(a,b,c):
    if a>b:
        if a>c:
            print(a, "is largest")
        elif c>a:
            print(c, "is the largest")
        else:
            print( a, "and", c, "are equal and greater than", b)
    if b>a:
        if b>c:
            print(b, "is largest")
        elif c>b:
            print(c, "is the largest")
        else:
            print( b, "and", c, "are equal and greater than", a)
    if a==b:
        if a>c:
            print( a, "and", b, "are equal and greater than", c)
        elif c>a:
            print(c, "is the largest")
        else:
            print("All three numbers are equal")
            
largest_num(20,20,60)
largest_num(80,20,0)
    

60 is the largest
80 is largest


12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.

In [18]:
def triangle_type(side1, side2, side3):
    if side1==side2==side3:
        print("Equilateral Triangle")
    elif side1==side2 or side1==side3 or side2==side3:
        print("Isosceles Triangle")
    else:
        print("Scalene Triangle")

triangle_type(12, 13, 14)
triangle_type(15, 20, 15)
triangle_type(11, 11, 11)
    

Scalene Triangle
Isosceles Triangle
Equilateral Triangle


13. Develop a program that checks if a year is a leap year and also if it is a century year.

In [20]:
#Definning a function to checl leap year
def if_leap(year):
    if year%100==0:
        print("It is a century year")
        if year%400==0:
            print("Leap Year")
        else:
            print("Not a leap year")
    elif year%4==0:
        print("Leap year")
    else:
        print("Not a leap year")
        
if_leap(2023)
if_leap(2024)
if_leap(2000)
if_leap(2100)

Not a leap year
Leap year
It is a century year
Leap Year
It is a century year
Not a leap year


14. Write a Python script to determine if a number is positive, negative, or zero.

In [25]:
#Define a function to check whether a number is positive or negative
def check_num():

    #Input number
    num = int(input("Input any number"))

    #Using if-else conditions to check the number
    if num>0:
        print("It is a positive number")
    elif num<0:
        print("It is a negative number")
    else:
        print("Neither positive nor negative, its zero!")

check_num()
check_num()
check_num()

Input any number 5


It is a positive number


Input any number -5


It is a negative number


Input any number 0


Neither positive nor negative, its zero!


15. Create a program to check if a person is a teenager (between 13 and 19 years old).

In [27]:
def if_teenager(age):
    if age>=13 and age<=19:
        print("Teenager")
    else:
        print("Not a teenager")
        
if_teenager(25)
if_teenager(16)

Not a teenager
Teenager


16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).

In [28]:
def angle_type(angle):
    if angle==90:
        print("Right angle")
    elif angle<90 and angle>0:
        print("Acute angle")
    elif angle>=90 and angle<=180:
        print("Obtuse angle")
    else:
        print("Invalid Input")
        
angle_type(30)
angle_type(90)
angle_type(150)

Acute angle
Right angle
Obtuse angle


17. Write a Python program to calculate the roots of a quadratic equation.

In [34]:
import math

def find_roots(a,b,c):

    # Calculate the discriminant
    discriminant = b**2 - 4*a*c

    # Check the discriminant to determine the nature of roots
    if discriminant > 0:
        # Two real and distinct roots
        root1 = (-b + math.sqrt(discriminant)) / (2*a)
        root2 = (-b - math.sqrt(discriminant)) / (2*a)
        print("Root 1 =", root1)
        print("Root 2 =", root2)
    elif discriminant == 0:
        # One real root (repeated)
        root = -b / (2*a)
        print("Root =", root)
    else:
        # Complex roots
        real_part = -b / (2*a)
        imaginary_part = math.sqrt(abs(discriminant)) / (2*a)
        print("Root 1 =", real_part, "+", imaginary_part, "i")
        print("Root 2 =", real_part, "-", imaginary_part, "i")
        
find_roots(1,8,3)
find_roots(2,3,4)

Root 1 = -0.3944487245360109
Root 2 = -7.60555127546399
Root 1 = -0.75 + 1.1989578808281798 i
Root 2 = -0.75 - 1.1989578808281798 i


18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2
for Tuesday, etc.).

In [35]:
def weekis(n):
    if n==1:
        print("Monday")
    elif n==2:
        print("Tuesday")
    elif n==3:
        print("Wednesday")
    elif n==4:
        print("Thursday")
    elif n==5:
        print("Friday")
    elif n==6:
        print("Saturday")
    elif n==7:
        print("Sunday")
    else:
        print("Invalid Input")
        
weekis(4)
weekis(1)

Thursday
Monday


19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400.

In [36]:
#Definning a function to checl leap year
def if_leap(year):
    if year%100==0:
        if year%400==0:
            print("Leap Year and evenly divided by 400")
        else:
            print("Not a leap year")
    elif year%4==0:
        print("Leap year")
    else:
        print("Not a leap year")
        
if_leap(2023)
if_leap(2024)
if_leap(2000)
if_leap(2100)

Not a leap year
Leap year
Leap Year and evenly divided by 400
Not a leap year


20. Develop a program that checks if a given number is prime or not using nested if-else statements.

In [37]:
def isprime(num):
    if num>1:
        for i in range(2,int(num**0.5)+1):
            if num%i==0:
                print("The given number is not a prime")
                break
        else:
            print("The given number is prime")
    else:
        print("The given number is not a prime")
        
        
isprime(33)
isprime(23)

The given number is not a prime
The given number is prime


Elif Statements:

21. Write a Python program to assign grades based on different ranges of scores using elif statements.

In [38]:
def score_to_grade(score):
    if score>=85 and score<=100:
        print("Grade A")
    elif score>=70 and score<=84:
        print("Grade B")
    elif score>=55 and score<=69:
        print("Grade C")
    elif score>=40 and score<=54:
        print("Grade D")
    elif score<=39 and score>=0:
        print("Grade E")
    else:
        print("Invalid Score Entered")
        
score_to_grade(56.4)
score_to_grade(86.3)
score_to_grade(895)

Grade C
Grade A
Invalid Score Entered


22. Implement a program to determine the type of a triangle based on its angles.

In [39]:
def triangle_type(a,b,c):
    if a<90 and b<90 and c<90:
        print("Acute-angled triangle")
    elif a==90 or b==90 or c==90:
        print("Right-angled triangle")
    elif a>90 or b>90 or c>90:
        print("Obtuse-angled triangle")
    else:
        print("Invalid input")
        
triangle_type(50,60,70)
triangle_type(100,20,60)

    
        

Acute-angled triangle
Obtuse-angled triangle


23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using
elif statements.

In [40]:
def check_bmi(height, weight):
    bmi = weight/(height**2)
    
    if bmi<18.5:
        print("Underweight")
    elif bmi>=18.5 and bmi<25:
        print("Healthy")
    elif bmi>=25 and bmi<30:
        print("Overweight")
    elif bmi>=30:
        print("Obese")
    else:
        print("Invalid Input")

check_bmi(1.56,60)

Healthy


24. Create a program that determines whether a given number is positive, negative, or zero using elif
statements.

In [41]:
def check_num(n):
    if n>0:
        print("positive")
    elif n<0:
        print("negative")
    else:
        print("Zero")

check_num(0)
check_num(-5)
check_num(2)
            


Zero
negative
positive


25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif
statements.

In [45]:
def check_char(character):

    if character.isupper():
        print(f"{character} is an uppercase letter.")
    elif character.islower():
        print(f"{character} is a lowercase letter.")
    elif not character.isalnum():
        print(f"{character} is a special character.")
    else:
        print(f"{character} is neither uppercase nor lowercase.")
        
check_char('30')
check_char('j')
check_char('*')

30 is neither uppercase nor lowercase.
j is a lowercase letter.
* is a special character.


26. Implement a program to calculate the discounted price based on different purchase amounts using elif
statements.

In [47]:
def discounted_price(amnt):
    if amnt>5000: 
        discounted_price = amnt-0.2*amnt
    elif amnt>1000:
        discounted_price = amnt-0.1*amnt
    elif amnt>500:
        discounted_price = amnt-0.05*amnt
        
    print("Discounted price is:",  discounted_price)
    
discounted_price(7000)
discounted_price(1200)


Discounted price is: 5600.0
Discounted price is: 1080.0


27. Develop a program to calculate the electricity bill based on different consumption slabs using elif
statements.

In [49]:
def bill(units):
    if units<100:
        bill = units*2.5
    elif units>=100 and units<200:
        bill = units*3.0
    else:
        bill = units*5.0
        
    print("Bill is:", bill)

bill(90)
bill(120)
bill(800)

Bill is: 225.0
Bill is: 360.0
Bill is: 4000.0


28. Create a program to determine the type of quadrilateral based on its angles and sides using elif
statements.

In [54]:
def quad_type(a1,a2,a3,a4,s1,s2,s3,s4):

# Check the type of quadrilateral based on angles and sides
    if a1 == a2 == a3 == a4 == 90:
        if s1 == s2 == s3 == s4:
            print("It is a square.")
        else:
            print("It is a rectangle.")
    elif ((a1 == a2) and (a3 == a4)) or ((a1 == a3) and (a2 == a4)) or ((a1 == a4) and (a3 == a2)) :
        print("It is a parallelogram.")
    elif s1 == s2 == s3 == s4:
        print("It is a rhombus.")
    else:
        print("It is a general quadrilateral.")
        
quad_type(100, 80, 100, 80, 7,8,7,8)
quad_type(90, 90, 90, 90, 7,8,7,8)


It is a parallelogram.
It is a rectangle.


29. Write a Python script to determine the season based on a user-provided month using elif statements.

In [55]:
def season_is(month):
    
    if 3 <= month <= 5:
        print("Spring")
    elif 6 <= month <= 8:
        print("Summer")
    elif 9 <= month <= 11:
        print("Autumn")
    elif month == 12 or month == 1 or month == 2:
        print("Winter")
    else:
        print("Invalid month")

season_is(8)
season_is(12)

Summer
Winter


30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using
elif statements.

In [56]:
def year_month(year, month):
    if year%100==0:
        if year%400==0:
            print("Leap Year")
        else:
            print("Common Year")
    elif year%4==0:
        print("Leap year")
    else:
        print("Common year")
        
    if month==1 or 3 or 5 or 7 or 8 or 10 or 12:
        print("31 days month")
    elif month==4 or 6 or 9 or 11:
        print("30 days month")
    elif month==2:
        print("29 or 28 days month")
    else:
        print("Invalid input")
        
year_month(2014, 7)


Common year
31 days month


Basic Level:

1. Write a Python program that checks if a given number is positive, negative, or zero.

In [57]:
def check_num(n):
    if n>0:
        print("positive")
    elif n<0:
        print("negative")
    else:
        print("Zero")

check_num(0)
check_num(-5)
check_num(2)

Zero
negative
positive


2. Create a program to determine if a person is eligible to vote based on their age.

In [58]:
#Defining a function to check the voting eligibility

def vote_elig(age):
    if age>=18:
        print("Eligible to vote")
    else:
        print("Not eligible to vote")
vote_elig(22)
vote_elig(12)

Eligible to vote
Not eligible to vote


3. Write a program to find the maximum of two given numbers using conditional statements

In [62]:
#Defining a function that tells the maximum of the two numbers
def max(num1, num2):
    

    if num1>num2:
        print(num1, "is maxumum")
    elif num2>num1:
        print(num2, "is maximum")
    else:
        print("Equal")
        
max(2,4)
max(8,2)
max(3,3)

4 is maximum
8 is maxumum
Equal


4. Develop a program that calculates the grade of a student based on their exam score.

In [63]:
def score_to_grade(score):
    if score>=85 and score<=100:
        print("Grade A")
    elif score>=70 and score<=84:
        print("Grade B")
    elif score>=55 and score<=69:
        print("Grade C")
    elif score>=40 and score<=54:
        print("Grade D")
    elif score<=39 and score>=0:
        print("Grade E")
    else:
        print("Invalid Score Entered")
        
score_to_grade(56.4)
score_to_grade(86.3)
score_to_grade(895)

Grade C
Grade A
Invalid Score Entered


5. Create a program that checks if a year is a leap year or not.

In [65]:
def if_leap(year):
    if year%100==0:
        if year%400==0:
            print("Leap Year")
        else:
            print("Not a leap year")
    elif year%4==0:
        print("Leap year")
    else:
        print("Not a leap year")
        
if_leap(2024)

Leap year


6. Write a program to classify a triangle based on its sides' lengths.

In [66]:
def triangle_type(side1, side2, side3):
    if side1==side2==side3:
        print("Equilateral Triangle")
    elif side1==side2 or side1==side3 or side2==side3:
        print("Isosceles Triangle")
    else:
        print("Scalene Triangle")

triangle_type(12, 13, 14)
triangle_type(15, 20, 15)
triangle_type(11, 11, 11)

Scalene Triangle
Isosceles Triangle
Equilateral Triangle


7. Build a program that determines the largest of three given numbers.

In [67]:
def largest_num(a,b,c):
    if a>b and a>c:
        print(a, " is the greatest")
    elif b>a and b>c:
        print(b, " is the greatest")
    elif c>a and c>b:
        print(c, " is the greatest")
    
largest_num(2,3,5)
largest_num(9,2,11)

5  is the greatest
11  is the greatest


8. Develop a program that checks whether a character is a vowel or a consonant.

In [68]:
def check_vowel_cons(char):
    if char in 'AEIOUaeiou':
        print(char, "is a vowel")
    else:
        print(char, "is a consonant")

check_vowel_cons('N')
check_vowel_cons('U')

N is a consonant
U is a vowel


9. Create a program to calculate the total cost of a shopping cart based on discounts.

In [71]:
def discounted_price(amnt):
    if amnt>5000: 
        discounted_price = amnt-0.2*amnt
    elif amnt>1000:
        discounted_price = amnt-0.1*amnt
    elif amnt>500:
        discounted_price = amnt-0.05*amnt
        
    print("Discounted price is:",  discounted_price)
    
discounted_price(7000)
discounted_price(1200)

Discounted price is: 5600.0
Discounted price is: 1080.0


10. Write a program that checks if a given number is even or odd.

In [70]:
def check_odd_even(num):
    if num%2==0:
        print(num, "is even")
    else:
        print(num, "is odd")

check_odd_even(55)
check_odd_even(22)

55 is odd
22 is even


Intermediate Level:

11. Write a program that calculates the roots of a quadratic equation .

In [75]:
import math

def find_roots(a,b,c):

    # Calculate the discriminant
    discriminant = b**2 - 4*a*c

    # Check the discriminant to determine the nature of roots
    if discriminant > 0:
        # Two real and distinct roots
        root1 = (-b + math.sqrt(discriminant)) / (2*a)
        root2 = (-b - math.sqrt(discriminant)) / (2*a)
        print("Root 1 =", root1)
        print("Root 2 =", root2)
    elif discriminant == 0:
        # One real root (repeated)
        root = -b / (2*a)
        print("Root =", root)
    else:
        # Complex roots
        real_part = -b / (2*a)
        imaginary_part = math.sqrt(abs(discriminant)) / (2*a)
        print("Root 1 =", real_part, "+", imaginary_part, "i")
        print("Root 2 =", real_part, "-", imaginary_part, "i")
        
find_roots(1,8,3)
find_roots(2,3,4)

Root 1 = -0.3944487245360109
Root 2 = -7.60555127546399
Root 1 = -0.75 + 1.1989578808281798 i
Root 2 = -0.75 - 1.1989578808281798 i


12. Create a program that determines the day of the week based on the day number (1-7).

In [76]:
def weekis(n):
    if n==1:
        print("Monday")
    elif n==2:
        print("Tuesday")
    elif n==3:
        print("Wednesday")
    elif n==4:
        print("Thursday")
    elif n==5:
        print("Friday")
    elif n==6:
        print("Saturday")
    elif n==7:
        print("Sunday")
    else:
        print("Invalid Input")
        
weekis(4)
weekis(1)

Thursday
Monday


13. Develop a program that calculates the factorial of a given number using recursion.

In [74]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)
    
factorial(3)

6

14. Write a program to find the largest among three numbers without using the `max()` function.

In [72]:
def largest_num(a,b,c):
    if a>b and a>c:
        print(a, " is the greatest")
    elif b>a and b>c:
        print(b, " is the greatest")
    elif c>a and c>b:
        print(c, " is the greatest")
    
largest_num(2,3,5)
largest_num(9,2,11)

5  is the greatest
11  is the greatest


15. Create a program that simulates a basic ATM transaction menu.

In [1]:
# Initialize the account balance
balance = 1000.0

# Main program loop
while True:
    # Display the ATM menu
    print("ATM Menu:")
    print("1. Check Balance")
    print("2. Make Withdrawal")
    print("3. Quit")

    # Get user input for menu choice
    choice = input("Enter your choice (1/2/3): ")

    if choice == '1':
        print(f"Your account balance is ${balance:.2f}")
    elif choice == '2':
        withdrawal_amount = float(input("Enter the withdrawal amount: $"))
        if withdrawal_amount > balance:
            print("Insufficient funds. Cannot withdraw.")
        else:
            balance -= withdrawal_amount
            print(f"Withdrew ${withdrawal_amount:.2f}. Your new balance is ${balance:.2f}")
    elif choice == '3':
        print("Thank you for using the ATM. Goodbye!")
        break
    else:
        print("Invalid choice. Please select a valid option (1/2/3).")

ATM Menu:
1. Check Balance
2. Make Withdrawal
3. Quit


Enter your choice (1/2/3):  2
Enter the withdrawal amount: $ 400


Withdrew $400.00. Your new balance is $600.00
ATM Menu:
1. Check Balance
2. Make Withdrawal
3. Quit


Enter your choice (1/2/3):  1


Your account balance is $600.00
ATM Menu:
1. Check Balance
2. Make Withdrawal
3. Quit


Enter your choice (1/2/3):  3


Thank you for using the ATM. Goodbye!


16. Build a program that checks if a given string is a palindrome or not.

In [2]:
def check_palindrome():
    string = input("Enter any string: ").lower()
    if string == string[::-1]:
        print("It is a palindrome")
    else:
        print("Not a Palindrome")
              

check_palindrome()
check_palindrome()

Enter any string:  Sha;linii


Not a Palindrome


Enter any string:  Naman


It is a palindrome


17. Write a program that calculates the average of a list of numbers, excluding the smallest and largest values.

In [9]:
def avg_list(lst):
    lst.sort()
    del lst[0]
    del lst[-1]
    avg = sum(lst)/len(lst)
    
    return avg
    
avg_list([5,6,4,1,3,2])

3.5

18. Develop a program that converts a given temperature from Celsius to Fahrenheit

In [11]:
def cel_to_far(c):
    f = c*1.8 + 32
    return f

cel_to_far(100)

212.0

19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division.

In [20]:
def calculator(num1, op , num2):
    if op == '+':
        print(num1+num2)
    if op == '-':
        print(num1-num2)
    if op =='*':
        print(num1*num2)
    if op == '/':
        print(num1/num2)
        
calculator(34,'+', 45)
    

79


20. Write a program that determines the roots of a cubic equation using the Cardano formula.

In [1]:
import math
def cbrt(a,b,c,d):
    delta0 = b**2 - 3*a*c
    delta1 = 2*b**3 - 9*a*b*c + 27*a**2*d
    C = ((delta1 + math.sqrt(delta1**2 - 4*delta0**3)) / 2)**(1/3)
    
    root1 = (-1 / (3*a)) * (b + C + delta0/C)
    root2 = (-1 / (3*a)) * (b + complex(-0.5, math.sqrt(3)/2) * C + complex(-0.5, -math.sqrt(3)/2) * delta0/C)
    root3 = (-1 / (3*a)) * (b + complex(-0.5, -math.sqrt(3)/2) * C + complex(-0.5, math.sqrt(3)/2) * delta0/C)
    
    print(f"Root 1: {root1:.4f}")
    print(f"Root 2: {root2:.4f}")
    print(f"Root 3: {root3:.4f}")
    
    
cbrt(5,4,2,3)

Root 1: -1.0000
Root 2: 0.1000-0.7681j
Root 3: 0.1000+0.7681j


Advanced Level:

21. Create a program that calculates the income tax based on the user's income and tax brackets.

In [5]:

def calculate(amount, percent):
    return (amount * percent) / 100
  
def calculate_income_tax(total_income: 
                         float) -> float:
  
    if total_income <= 250000:
        return 0
    elif total_income <= 500000:
        return calculate(total_income - 
                         250000, 5)
    elif total_income <= 750000:
        return calculate(total_income - 
                         500000, 10) + 12500
    elif total_income <= 1000000:
        return calculate(total_income - 
                         750000, 15) + 37500
    elif total_income <= 1250000:
        return calculate(total_income - 
                         1000000, 20) + 75000
    elif total_income <= 1500000:
        return calculate(total_income - 
                         1250000, 25) + 125000
    else:
        return calculate(total_income - 
                         1500000, 30) + 187500
    
calculate_income_tax(500000)

12500.0

22. Write a program that simulates a rock-paper-scissors game against the computer

In [3]:
import random

# Define the choices
choices = ["rock", "paper", "scissors"]

# Get user's choice
user_choice = input("Enter your choice (rock, paper, or scissors): ").lower()

# Check if the user's choice is valid
if user_choice not in choices:
    print("Invalid choice. Please choose from rock, paper, or scissors.")
else:
    # Generate a random choice for the computer
    computer_choice = random.choice(choices)

    # Display the choices
    print(f"Your choice: {user_choice}")
    print(f"Computer's choice: {computer_choice}")

    # Determine the winner
    if user_choice == computer_choice:
        print("It's a tie!")
    elif (
        (user_choice == "rock" and computer_choice == "scissors")
        or (user_choice == "paper" and computer_choice == "rock")
        or (user_choice == "scissors" and computer_choice == "paper")
    ):
        print("You win!")
    else:
        print("Computer wins!")

Enter your choice (rock, paper, or scissors):  rock


Your choice: rock
Computer's choice: paper
Computer wins!


23. Develop a program that generates a random password based on user preferences (length, complexity).

In [18]:
import random
import string

# Get user preferences
length = int(input("Enter the length of the password: "))
use_lowercase = input("Include lowercase letters? (yes/no): ").lower() == "yes"
use_uppercase = input("Include uppercase letters? (yes/no): ").lower() == "yes"
use_digits = input("Include digits? (yes/no): ").lower() == "yes"
use_special_chars = input("Include special characters? (yes/no): ").lower() == "yes"

# Define character sets
characters = ""
if use_lowercase:
    characters += string.ascii_lowercase
if use_uppercase:
    characters += string.ascii_uppercase
if use_digits:
    characters += string.digits
if use_special_chars:
    characters += string.punctuation

# Check if at least one character set is selected
if not characters:
    print("Please select at least one character set.")
else:
    # Generate the password
    password = ''.join(random.choice(characters)  for i in range(length))
    print("Generated Password:", password)

Enter the length of the password:  5
Include lowercase letters? (yes/no):  no
Include uppercase letters? (yes/no):  yes
Include digits? (yes/no):  no
Include special characters? (yes/no):  yes


Generated Password: /O`,J


24. Create a program that implements a simple text-based adventure game with branching scenarios.

In [19]:
print("Welcome to the Adventure Game!")

# Start of the game
print("\nYou find yourself standing in front of a mysterious cave.")
choice = input("Do you want to enter the cave? (yes/no): ").lower()

if choice == "yes":
    print("\nYou enter the cave and it's very dark inside.")
    choice = input("Do you want to use a flashlight? (yes/no): ").lower()

    if choice == "yes":
        print("\nYou turn on the flashlight and see a fork in the path ahead.")
        choice = input("Do you want to go left or right? (left/right): ").lower()

        if choice == "left":
            print("\nYou encounter a treasure chest filled with gold! You're rich!")
        elif choice == "right":
            print("\nYou stumble into a trap and fall into a pit. Game over!")
        else:
            print("Invalid choice. Game over!")

    elif choice == "no":
        print("\nYou decide to proceed in the dark. Unfortunately, you trip and fall into a pit. Game over!")

    else:
        print("Invalid choice. Game over!")

elif choice == "no":
    print("\nYou decide not to enter the cave and go home instead. Game over!")

else:
    print("Invalid choice. Game over!")

print("\nThanks for playing the Adventure Game!")

Welcome to the Adventure Game!

You find yourself standing in front of a mysterious cave.


Do you want to enter the cave? (yes/no):  no



You decide not to enter the cave and go home instead. Game over!

Thanks for playing the Adventure Game!


25. Build a program that solves a linear equation  for x, considering different cases.

In [17]:
def sol_linear(a, b):
    if a == 0 and b == 0:
        print("Infinite solutions. The equation is trivial (0*x = 0).")

    elif a == 0 and b != 0:
        print("No solution. The equation is inconsistent (0*x + b = 0, where b is not 0).")

    else:
        x = -b / a
        print(f"The solution to the linear equation {a}*x + {b} = 0 is x = {x:.2f}")
        
sol_linear(5,1)

The solution to the linear equation 5*x + 1 = 0 is x = -0.20


26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.

In [1]:
questions = [
    {
        "question": "Who is the Prime Minister of India?",
        "options": ["A) Draupadi Murmu", "B) Narendra Modi", "C) Gandhiji", "D) Manmohan Singh"],
        "correct_answer": "B",
    },
    {
        "question": "Who is the founder of Facebook?",
        "options": ["A) Mark Zuckerberg", "B) Larry Page", "C) Gustav Van Rosuum", "D) Stieve Jobs"],
        "correct_answer": "A",
    },
    {
        "question": "Who is the Founder of PW Skills?",
        "options": ["A) Alakh pandey", "B) sunil varma", "C) sai charan", "D) Bhavani"],
        "correct_answer": "A",
    },
]

# Initialize the score
score = 0

# Quiz loop
for i, question in enumerate(questions, 1):
    print(f"\nQuestion {i}: {question['question']}")
    for option in question["options"]:
        print(option)
    
    user_answer = input("Your answer (A/B/C/D): ").upper()

    if user_answer == question["correct_answer"]:
        print("Correct!")
        score += 1
    else:
        print(f"Wrong! The correct answer is {question['correct_answer']}.")

# Display the final score
print("\nQuiz completed!")
print(f"Your score: {score}/{len(questions)}")


Question 1: Who is the Prime Minister of India?
A) Draupadi Murmu
B) Narendra Modi
C) Gandhiji
D) Manmohan Singh


Your answer (A/B/C/D):  b


Correct!

Question 2: Who is the founder of Facebook?
A) Mark Zuckerberg
B) Larry Page
C) Gustav Van Rosuum
D) Stieve Jobs


Your answer (A/B/C/D):  a


Correct!

Question 3: Who is the Founder of PW Skills?
A) Alakh pandey
B) sunil varma
C) sai charan
D) Bhavani


Your answer (A/B/C/D):  a


Correct!

Quiz completed!
Your score: 3/3


27. Develop a program that determines whether a given year is a prime number or not.

In [33]:
def check_prime(year):
    if year<=1:
        return False
    for i in range(2,int(year**0.5) +1):
        if year%i==0:
            return False
    return True

check_prime(2017)
    

True

28. Create a program that sorts three numbers in ascending order using conditional statements

In [26]:
def sort(a,b,c):
    if a<b:
        if b<c:
            print(a,b,c)
        else:
            if a<c:
                print(a,c,b)
            else:
                print(c,a,b)
    if a>b:
        if b>c:
            print(c,b,a)
        else:
            if a>c:
                print(b,c,a)
            else:
                print(b,a,c)
sort(4,5,1)
sort(23,11,23)

1 4 5
11 23 23


29. Build a program that determines the roots of a quartic equation using numerical methods.

In [24]:
import math

def find_roots(a,b,c):

    # Calculate the discriminant
    discriminant = b**2 - 4*a*c

    # Check the discriminant to determine the nature of roots
    if discriminant > 0:
        # Two real and distinct roots
        root1 = (-b + math.sqrt(discriminant)) / (2*a)
        root2 = (-b - math.sqrt(discriminant)) / (2*a)
        print("Root 1 =", root1)
        print("Root 2 =", root2)
    elif discriminant == 0:
        # One real root (repeated)
        root = -b / (2*a)
        print("Root =", root)
    else:
        # Complex roots
        real_part = -b / (2*a)
        imaginary_part = math.sqrt(abs(discriminant)) / (2*a)
        print("Root 1 =", real_part, "+", imaginary_part, "i")
        print("Root 2 =", real_part, "-", imaginary_part, "i")
        
find_roots(1,8,3)
find_roots(2,3,4)

Root 1 = -0.3944487245360109
Root 2 = -7.60555127546399
Root 1 = -0.75 + 1.1989578808281798 i
Root 2 = -0.75 - 1.1989578808281798 i


30. Write a program that calculates the BMI (Body Mass Index) and provides health recommendations based
on the user's input.

In [21]:
def check_bmi(height, weight):
    bmi = weight/(height**2)
    
    if bmi<18.5:
        print("Underweight")
    elif bmi>=18.5 and bmi<25:
        print("Healthy")
    elif bmi>=25 and bmi<30:
        print("Overweight")
    elif bmi>=30:
        print("Obese")
    else:
        print("Invalid Input")

check_bmi(1.56,60)

Healthy


Challenge Level:

31. Create a program that validates a password based on complexity rules (length, characters, etc.)

In [20]:
# Define password complexity rules
min_length = 8
requires_lowercase = True
requires_uppercase = True
requires_digit = True
requires_special_char = True

# Get user input for the password
password = input("Enter your password: ")

# Initialize error messages list
errors = []

# Check password length
if len(password) < min_length:
    errors.append(f"Password should be at least {min_length} characters long.")

# Check lowercase requirement
if requires_lowercase and not any(char.islower() for char in password):
    errors.append("Password should contain at least one lowercase letter.")

# Check uppercase requirement
if requires_uppercase and not any(char.isupper() for char in password):
    errors.append("Password should contain at least one uppercase letter.")

# Check digit requirement
if requires_digit and not any(char.isdigit() for char in password):
    errors.append("Password should contain at least one digit.")

# Check special character requirement
if requires_special_char and not any(char in "!@#$%^&*()_+[]{}|;:'\"<>,.?/~`" for char in password):
    errors.append("Password should contain at least one special character.")

# Check if there are any errors
if errors:
    print("\nPassword validation failed. Please correct the following issues:")
    for error in errors:
        print(error)
else:
    print("\nPassword is valid and meets the complexity requirements.")

Enter your password:  Shalini@0909



Password is valid and meets the complexity requirements.


32. Develop a program that performs matrix addition and subtraction based on user input.

In [21]:
# Input matrix dimensions
rows = int(input("Enter the number of rows for matrices: "))
cols = int(input("Enter the number of columns for matrices: "))

# Input two matrices
print("Matrix A:")
matrix_a = []
for i in range(rows):
    row = []
    for j in range(cols):
        element = float(input(f"Enter element at position ({i+1},{j+1}): "))
        row.append(element)
    matrix_a.append(row)

print("Matrix B:")
matrix_b = []
for i in range(rows):
    row = []
    for j in range(cols):
        element = float(input(f"Enter element at position ({i+1},{j+1}): "))
        row.append(element)
    matrix_b.append(row)

# Choose operation
operation = input("Choose operation (addition or subtraction): ").lower()

# Perform the chosen operation
result_matrix = []
if operation == "addition":
    for i in range(rows):
        row = []
        for j in range(cols):
            row.append(matrix_a[i][j] + matrix_b[i][j])
        result_matrix.append(row)
elif operation == "subtraction":
    for i in range(rows):
        row = []
        for j in range(cols):
            row.append(matrix_a[i][j] - matrix_b[i][j])
        result_matrix.append(row)
else:
    result_matrix = None
    print("Invalid operation!")

# Display the result
if result_matrix:
    print("Result:")
    for row in result_matrix:
        print(" ".join(map(str, row)))
else:
    print("Matrix dimensions are not compatible for the chosen operation.")

Enter the number of rows for matrices:  2
Enter the number of columns for matrices:  2


Matrix A:


Enter element at position (1,1):  1
Enter element at position (1,2):  2
Enter element at position (2,1):  3
Enter element at position (2,2):  4


Matrix B:


Enter element at position (1,1):  1
Enter element at position (1,2):  2
Enter element at position (2,1):  3
Enter element at position (2,2):  4
Choose operation (addition or subtraction):  addition


Result:
2.0 4.0
6.0 8.0


33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean
algorithm.

In [8]:
def gcd_euclidean(a, b):
    while b:
        a, b = b, a % b
    return a

gcd_euclidean(135, 30)

15

34. Build a program that performs matrix multiplication using nested loops and conditional statements

In [26]:
 # Function to multiply two matrices
def matrix_multiply(matrix1, matrix2):
    # Get the dimensions of the input matrices
    rows1, cols1 = len(matrix1), len(matrix1[0])
    rows2, cols2 = len(matrix2), len(matrix2[0])
    if cols1 != rows2:
        print("Matrix multiplication is not possible. Number of columns in matrix 1 must be equal to the number of rows in matrix 2.")
        return None

    # Initialize the result matrix with zeros
    result = [[0 for _ in range(cols2)] for _ in range(rows1)]

    # Perform matrix multiplication using nested loops
    for i in range(rows1):
        for j in range(cols2):
            for k in range(cols1):
                result[i][j] += matrix1[i][k] * matrix2[k][j]

    return result

# Example matrices for testing
matrix_A = [
    [2, 2, 3],
    [4, 5, 6]
]

matrix_B = [
    [7, 10],
    [9, 10],
    [11, 120]
]

# Perform matrix multiplication
result_matrix = matrix_multiply(matrix_A, matrix_B)

# Display the result matrix
if result_matrix:
    print("Resultant Matrix:")
    for row in result_matrix:
        print(row)

Resultant Matrix:
[65, 400]
[139, 810]


35. Create a program that simulates a basic text-based tic-tac-toe game against the computer

In [9]:
# Tic-Tac-Toe Program using
# random number in Python

# importing all necessary libraries
import numpy as np
import random
from time import sleep

# Creates an empty board


def create_board():
	return(np.array([[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]))

# Check for empty places on board


def possibilities(board):
	l = []

	for i in range(len(board)):
		for j in range(len(board)):

			if board[i][j] == 0:
				l.append((i, j))
	return(l)

# Select a random place for the player


def random_place(board, player):
	selection = possibilities(board)
	current_loc = random.choice(selection)
	board[current_loc] = player
	return(board)

# Checks whether the player has three
# of their marks in a horizontal row


def row_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a vertical row


def col_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a diagonal row


def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win

# Evaluates whether there is
# a winner or a tie


def evaluate(board):
	winner = 0

	for player in [1, 2]:
		if (row_win(board, player) or
				col_win(board, player) or
				diag_win(board, player)):

			winner = player

	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner

# Main function to start the game


def play_game():
	board, winner, counter = create_board(), 0, 1
	print(board)
	sleep(2)

	while winner == 0:
		for player in [1, 2]:
			board = random_place(board, player)
			print("Board after " + str(counter) + " move")
			print(board)
			sleep(2)
			counter += 1
			winner = evaluate(board)
			if winner != 0:
				break
	return(winner)


# Driver Code
print("Winner is: " + str(play_game()))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 0]
 [0 1 0]]
Board after 2 move
[[0 0 0]
 [2 0 0]
 [0 1 0]]
Board after 3 move
[[0 0 0]
 [2 0 1]
 [0 1 0]]
Board after 4 move
[[0 2 0]
 [2 0 1]
 [0 1 0]]
Board after 5 move
[[0 2 0]
 [2 1 1]
 [0 1 0]]
Board after 6 move
[[2 2 0]
 [2 1 1]
 [0 1 0]]
Board after 7 move
[[2 2 1]
 [2 1 1]
 [0 1 0]]
Board after 8 move
[[2 2 1]
 [2 1 1]
 [0 1 2]]
Board after 9 move
[[2 2 1]
 [2 1 1]
 [1 1 2]]
Winner is: 1


36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods.

In [2]:
num = 10
n1, n2 = 0, 1
print("Fibonacci Series:", n1, n2, end=" ")
for i in range(2, num):
    n3 = n1 + n2
    n1 = n2
    n2 = n3
    print(n3, end=" ")

print()

Fibonacci Series: 0 1 1 2 3 5 8 13 21 34 


37. Develop a program that calculates the nth term of the Fibonacci sequence using memoization.

In [17]:
def memoization_fib(n, memo={}):
    if n in memo:
        return memo[n]
    if n == 1:
        return 0
    if n==3 or n==2:
        return 1

    memo[n] = memoization_fib(n - 1, memo) + memoization_fib(n - 2, memo)
    return memo[n]

print("fibonacci of 1:  ", memoization_fib(1))
print("fibonacci of 3:  ", memoization_fib(3))
print("fibonacci of 20: ", memoization_fib(20))
print("fibonacci of 40: ", memoization_fib(40))

fibonacci of 1:   0
fibonacci of 3:   1
fibonacci of 20:  4181
fibonacci of 40:  63245986


38. Create a program that generates a calendar for a given month and year using conditional statements.

In [8]:
import calendar  
  
year = int(input ("Please enter the Year: ")) 
month = int(input ("Please enter the month: "))     
  
# Now, we will display the calendar  
print("The Calendar of: ", calendar.month(year, month)) 

Please enter the Year:  2023
Please enter the month:  9


The Calendar of:     September 2023
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30



39. Build a program that simulates a basic text-based blackjack game against the computer.

In [6]:
import random

card_categories = ['Hearts', 'Spades', 'Clubs', 'Spades']
cards_list = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King']
deck = [(card, category) for category in card_categories for card in cards_list]

def card_value(card):
    if card[0] in ['Jack', 'Queen', 'King']:
        return 10
    elif card[0] == 'Ace':
        return 11
    else:
        return int(card[0])
    
random.shuffle(deck)
player_card = [deck.pop(), deck.pop()]
dealer_card = [deck.pop(), deck.pop()]

while True:
    player_score = sum(card_value(card) for card in player_card)
    dealer_score = sum(card_value(card) for card in dealer_card)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("\n")
    choice = input('What do you want? ["play" to request another card, "stop" to stop]: ').lower()
    if choice == "play":
        new_card = deck.pop()
        player_card.append(new_card)
    elif choice == "stop":
        break
    else:
        print("Invalid choice. Please try again.")
        continue

    if player_score > 21:
        print("Cards Dealer Has:", dealer_card)
        print("Score Of The Dealer:", dealer_score)
        print("Cards Player Has:", player_card)
        print("Score Of The Player:", player_score)
        print("Dealer wins (Player Loss Because Player Score is exceeding 21)")
        break

while dealer_score < 17:
    new_card = deck.pop()
    dealer_card.append(new_card)
    dealer_score += card_value(new_card)

print("Cards Dealer Has:", dealer_card)
print("Score Of The Dealer:", dealer_score)
print("\n")

if dealer_score > 21:
    print("Cards Dealer Has:", dealer_card)
    print("Score Of The Dealer:", dealer_score)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("Player wins (Dealer Loss Because Dealer Score is exceeding 21)")
elif player_score > dealer_score:
    print("Cards Dealer Has:", dealer_card)
    print("Score Of The Dealer:", dealer_score)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("Player wins (Player Has High Score than Dealer)")
elif dealer_score > player_score:
    print("Cards Dealer Has:", dealer_card)
    print("Score Of The Dealer:", dealer_score)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("Dealer wins (Dealer Has High Score than Player)")
else:
    print("Cards Dealer Has:", dealer_card)
    print("Score Of The Dealer:", dealer_score)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("It's a tie.")


Cards Player Has: [('5', 'Clubs'), ('4', 'Clubs')]
Score Of The Player: 9




What do you want? ["play" to request another card, "stop" to stop]:  play


Cards Player Has: [('5', 'Clubs'), ('4', 'Clubs'), ('2', 'Spades')]
Score Of The Player: 11




What do you want? ["play" to request another card, "stop" to stop]:  play


Cards Player Has: [('5', 'Clubs'), ('4', 'Clubs'), ('2', 'Spades'), ('3', 'Clubs')]
Score Of The Player: 14




What do you want? ["play" to request another card, "stop" to stop]:  play


Cards Player Has: [('5', 'Clubs'), ('4', 'Clubs'), ('2', 'Spades'), ('3', 'Clubs'), ('4', 'Spades')]
Score Of The Player: 18




What do you want? ["play" to request another card, "stop" to stop]:  play


Cards Player Has: [('5', 'Clubs'), ('4', 'Clubs'), ('2', 'Spades'), ('3', 'Clubs'), ('4', 'Spades'), ('Ace', 'Clubs')]
Score Of The Player: 29




What do you want? ["play" to request another card, "stop" to stop]:  play


Cards Dealer Has: [('King', 'Hearts'), ('Ace', 'Spades')]
Score Of The Dealer: 21
Cards Player Has: [('5', 'Clubs'), ('4', 'Clubs'), ('2', 'Spades'), ('3', 'Clubs'), ('4', 'Spades'), ('Ace', 'Clubs'), ('4', 'Hearts')]
Score Of The Player: 29
Dealer wins (Player Loss Because Player Score is exceeding 21)
Cards Dealer Has: [('King', 'Hearts'), ('Ace', 'Spades')]
Score Of The Dealer: 21


Cards Dealer Has: [('King', 'Hearts'), ('Ace', 'Spades')]
Score Of The Dealer: 21
Cards Player Has: [('5', 'Clubs'), ('4', 'Clubs'), ('2', 'Spades'), ('3', 'Clubs'), ('4', 'Spades'), ('Ace', 'Clubs'), ('4', 'Hearts')]
Score Of The Player: 29
Player wins (Player Has High Score than Dealer)


40. Write a program that generates the prime factors of a given number using trial division.

In [14]:
def prime_trial(n):
    for i in range(2, n):
        if n%i==0:
            return False
            break
    return True

def prime_factors(n):
    prime_factors = []
    for i in range(2, n):
        if n%i==0 and prime_trial(i):
            prime_factors.append(i)
    return prime_factors


prime_factors(30)
            

[2, 3, 5]